### PR TITLE
Update input_lists.json

### PR DESCRIPTION
**Pull request by RichardScottOZ**
Things I am using!

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
Will post here when script is re-run and results embedded in webpage.

**Comment by JustinGOSSES** [comment]
FYI - there were some full links included that I shortened as it needs to be `username_or_orgname/repo_name`

**Comment by JustinGOSSES** [comment]
Updated: https://softwareunderground.github.io/open_geosciene_code_projects_viz/explore/

**Comment by RichardScottOZ** [comment]
Thanks, wasn't sure if you had left those for a reason or not.

**Pull request merged**
